name: Clean Preview

on:
  pull_request:
    branches: [ master ]
    types: [closed]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout gh-pages
      uses: actions/checkout@v2
      with:
        ref: gh-pages

    - name: Clean preview
      uses: JesseTG/rm@v1.0.2
      with:
        path: ./pr/${{ github.event.pull_request.head.ref }}/

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./
